-- +goose Up
-- A JPA-clean table: lower_snake_case throughout, a timestamp WITH time zone,
-- and the version column Hibernate's optimistic locking needs.
CREATE TABLE widget (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    version    bigint NOT NULL DEFAULT 0
);

-- +goose Down
DROP TABLE widget;
