package dbtest_test

import (
	"testing"
	"testing/fstest"

	"github.com/squall-chua/go-boot/db/dbtest"
)

// A JPA-clean table: lower_snake_case throughout, a timestamp WITH time zone,
// and the version column Hibernate's optimistic locking needs.
var migrations = fstest.MapFS{
	"00001_widget.sql": &fstest.MapFile{Data: []byte(`-- +goose Up
CREATE TABLE widget (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       varchar(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    version    bigint NOT NULL DEFAULT 0
);
`)},
}

// Four instances in parallel is the case the library's own defaults fail:
// two collide on initdb, and isolating only the data path still fails on the
// password file. If Start ever loses a line of the recipe, this is what says
// so.
func TestStartRunsFourInParallel(t *testing.T) {
	for _, name := range []string{"one", "two", "three", "four"} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			pool := dbtest.Start(t, migrations)
			var n int
			if err := pool.QueryRowContext(t.Context(), "SELECT count(*) FROM widget").Scan(&n); err != nil {
				t.Fatalf("the migration did not run: %v", err)
			}
		})
	}
}

func TestStartWithNilMigrationsLeavesAnEmptySchema(t *testing.T) {
	t.Parallel()
	pool := dbtest.Start(t, nil)
	var n int
	err := pool.QueryRowContext(t.Context(),
		"SELECT count(*) FROM information_schema.tables WHERE table_schema = 'public'").Scan(&n)
	if err != nil {
		t.Fatal(err)
	}
	if n != 0 {
		t.Errorf("nil migrations left %d tables behind, want 0", n)
	}
}

// The clean schema must pass WITH goose's bookkeeping table present, because
// that table has a timestamp with no time zone and no version column. The
// skip is what keeps the lint usable on every schema go-boot creates.
func TestLintJPAConventionsPassesACleanSchema(t *testing.T) {
	t.Parallel()
	dbtest.LintJPAConventions(t, dbtest.Start(t, migrations))
}
