package dbtest

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"testing/fstest"
)

// The three findings, each from a table that breaks one rule. Tested against
// the unexported lint, because the exported one reports through testing.TB
// and a test cannot assert that a *testing.T was failed on purpose.
func TestLintJPAConventionsReportsEachViolation(t *testing.T) {
	t.Parallel()
	pool := Start(t, nil)

	for _, ddl := range []string{
		// A quoted camelCase identifier is what Hibernate's naming strategy
		// never produces, so a Go-side one breaks the shared schema.
		`CREATE TABLE "camelCase" (id bigint, version bigint)`,
		// LocalDateTime maps to this, and the UTC offset is lost.
		`CREATE TABLE no_zone (id bigint, version bigint, created_at timestamp)`,
		// No version column, so a Hibernate write commits over a Go write
		// and neither side raises anything.
		`CREATE TABLE unversioned (id bigint)`,
	} {
		if _, err := pool.ExecContext(t.Context(), ddl); err != nil {
			t.Fatalf("%s: %v", ddl, err)
		}
	}

	findings, err := lintJPAConventions(t.Context(), pool, skippedTables)
	if err != nil {
		t.Fatal(err)
	}
	joined := strings.Join(findings, "\n")
	for _, want := range []string{"camelCase", "no_zone.created_at", "unversioned"} {
		if !strings.Contains(joined, want) {
			t.Errorf("lint missed %s:\n%s", want, joined)
		}
	}
	if len(findings) != 3 {
		t.Errorf("got %d findings, want one per rule:\n%s", len(findings), joined)
	}
}

// A schema Hibernate itself generated must produce nothing, and the
// hand-rolled version of the same two tables must produce findings. That pair
// is the whole claim the lint makes.
func TestLintJPAConventionsPassesHibernatesSchemaAndFailsTheHandRolledOne(t *testing.T) {
	t.Parallel()
	pool := Start(t, nil)

	ddl, err := os.ReadFile(filepath.Join("testdata", "hibernate_schema.sql"))
	if err != nil {
		t.Fatal(err)
	}
	if _, err := pool.ExecContext(t.Context(), string(ddl)); err != nil {
		t.Fatal(err)
	}

	findings, err := lintJPAConventions(t.Context(), pool, skippedTables)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 0 {
		t.Errorf("Hibernate's own schema was flagged:\n%s", strings.Join(findings, "\n"))
	}

	// The same two tables, hand-rolled by someone who had not read the page:
	// a quoted camelCase column, a LocalDateTime timestamp, and no version.
	for _, stmt := range []string{
		`DROP TABLE customer, order_line`,
		`CREATE TABLE customer (id bigint, "firstName" varchar(255), created_at timestamp, version bigint)`,
		`CREATE TABLE order_line (id bigint, unit_price numeric(38,2))`,
	} {
		if _, err := pool.ExecContext(t.Context(), stmt); err != nil {
			t.Fatalf("%s: %v", stmt, err)
		}
	}
	findings, err = lintJPAConventions(t.Context(), pool, skippedTables)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 3 {
		t.Errorf("the hand-rolled schema got %d findings, want one per rule:\n%s",
			len(findings), strings.Join(findings, "\n"))
	}
}

// The claim in skippedTables, run: this clean schema is one go-boot created,
// and with nothing skipped the lint fails it.
func TestTheBookkeepingSkipIsLoadBearing(t *testing.T) {
	t.Parallel()
	pool := Start(t, fstest.MapFS{"00001_widget.sql": &fstest.MapFile{Data: []byte(`-- +goose Up
CREATE TABLE widget (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) with time zone NOT NULL DEFAULT now(),
    version    bigint NOT NULL DEFAULT 0
);
`)}})

	findings, err := lintJPAConventions(t.Context(), pool, skippedTables)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 0 {
		t.Errorf("a clean schema was flagged:\n%s", strings.Join(findings, "\n"))
	}

	// The same schema, linted with nothing skipped.
	findings, err = lintJPAConventions(t.Context(), pool, nil)
	if err != nil {
		t.Fatal(err)
	}
	joined := strings.Join(findings, "\n")
	if !strings.Contains(joined, "goose_db_version") {
		t.Errorf("without the skip the lint should fail on goose's own table, got:\n%s", joined)
	}
}
