-- +goose Up
-- The three conventions here are not JPA-specific, so they are the default:
-- timestamptz rather than timestamp, an identity id rather than a sequence,
-- and lower_snake_case identifiers. They are what a Spring Data JPA service
-- sharing this database expects, and they are right on their own anyway.
CREATE TABLE greeting (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Uncomment when a Spring Data JPA service shares this database and its
    -- entity carries @Version. Then EVERY Go UPDATE to this table must write
    -- `version = version + 1`, or Hibernate commits over your write and
    -- neither side raises an error. See docs/jpa-interop.md in go-boot.
    -- version bigint NOT NULL DEFAULT 0,
    lang text NOT NULL UNIQUE,
    message text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO greeting (lang, message) VALUES ('en', 'hello');

-- +goose Down
DROP TABLE greeting;
